class AppModel {
  final String name, image, description, category;
  final double rating;
  final int review, price;
  bool isCheck;
  AppModel({
    required this.name,
    required this.image,
    required this.description,
    required this.category,
    required this.rating,
    required this.review,
    required this.price,
    required this.isCheck,
  });
}

List<AppModel> groceryItemsList = [
  AppModel(
    name: "Banana",
    image: "assets/images/fruits.png",
    description: "",
    category: "fruits",
    rating: 8.9,
    review: 5,
    price: 12,
    isCheck: true,
  ),
  AppModel(
    name: "Orange",
    image: "assets/images/beverages.png",
    description: "",
    category: "fruits",
    rating: 8.9,
    review: 5,
    price: 12,
    isCheck: true,
  ),
  AppModel(
    name: "Banana",
    image: "assets/images/laundry.png",
    description: "",
    category: "fruits",
    rating: 8.9,
    review: 5,
    price: 12,
    isCheck: true,
  ),
  AppModel(
    name: "Banana",
    image: "assets/images/milk.png",
    description: "",
    category: "fruits",
    rating: 8.9,
    review: 5,
    price: 12,
    isCheck: true,
  ),
  AppModel(
    name: "Banana",
    image: "assets/images/fruits.png",
    description: "",
    category: "fruits",
    rating: 8.9,
    review: 5,
    price: 12,
    isCheck: true,
  ),
  AppModel(
    name: "Banana",
    image: "assets/images/fruits.png",
    description: "",
    category: "fruits",
    rating: 8.9,
    review: 5,
    price: 12,
    isCheck: true,
  ),
  AppModel(
    name: "Banana",
    image: "assets/images/fruits.png",
    description: "",
    category: "fruits",
    rating: 8.9,
    review: 5,
    price: 12,
    isCheck: true,
  ),
  AppModel(
    name: "Banana",
    image: "assets/images/fruits.png",
    description: "",
    category: "fruits",
    rating: 8.9,
    review: 5,
    price: 12,
    isCheck: true,
  ),
  AppModel(
    name: "Banana",
    image: "assets/images/fruits.png",
    description: "",
    category: "fruits",
    rating: 8.9,
    review: 5,
    price: 12,
    isCheck: true,
  ),
  AppModel(
    name: "Banana",
    image: "assets/images/fruits.png",
    description: "",
    category: "fruits",
    rating: 8.9,
    review: 5,
    price: 12,
    isCheck: true,
  ),
  AppModel(
    name: "Banana",
    image: "assets/images/fruits.png",
    description: "",
    category: "fruits",
    rating: 8.9,
    review: 5,
    price: 12,
    isCheck: true,
  ),
  AppModel(
    name: "Banana",
    image: "assets/images/fruits.png",
    description: "",
    category: "fruits",
    rating: 8.9,
    review: 5,
    price: 12,
    isCheck: true,
  ),
];
